---
name: Ejercicio 4

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    name: Ejercicio 4
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set Up
        uses: actions/setup-java@v3
        with:
          java-version: 17
          cache: maven
          distribution: 'temurin'
      - name: Build With Maven
        run: mvn -B package
      - name: Run Tests
        run: |
          mvn -B test
          if [ $? -ne 0 ]; then
          echo "Tests failed"
          exit 1
          fi
      - name: Super Linter
        uses: github/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_GOOGLE_JAVA_FORMAT: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: always()
        with:
          fail_on_errors: true