name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    name: Ejercicio 4
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set Up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 17
        cache: maven
        distribution: 'temurin'
    - name: Build With Maven
      run: mvn -B package
    - name: Run Tests
      run: mvn -B test
    - name: Super Linter
      uses: github/super-linter@v4
      env:
        VALIDATE_ALL_CODEBASE: true
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
