name: Promote to main if lint and tests are OK

on:
  push:
    branches:
      - develop

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: 'main'

      - name: Merge changes from develop
        run: git merge --ff-only origin/develop

      - name: Push changes to main
        uses: ad-m/github-push-action@master
        with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        force: true
